import 'package:flutter/material.dart';
import '../services/api_service.dart';
import '../models/payment.dart';

class PaymentsPage extends StatefulWidget {
  const PaymentsPage({super.key});

  @override
  State<PaymentsPage> createState() => _PaymentsPageState();
}

class _PaymentsPageState extends State<PaymentsPage> {
  final ApiService _apiService = ApiService();

  // Placeholder orderId and amount - In a real app, these would come from the current order
  final String _placeholderOrderId = 'a1b2c3d4-e5f6-7890-1234-567890abcdef'; 
  final double _placeholderAmount = 50.00;

  Future<void> _makePayment(String method) async {
    final payment = Payment(
      id: '', // ID is usually generated by the backend
      orderId: _placeholderOrderId,
      method: method,
      amount: _placeholderAmount,
      status: 'PENDING', // Initial status
    );

    try {
      await _apiService.createPayment(payment);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Pagamento $method enviado com sucesso!')),
      );
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Erro ao enviar pagamento: $e')),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Pagamentos'),
      ),
      body: ListView(
        padding: const EdgeInsets.all(16.0),
        children: [
          const Text(
            'Escolha a forma de pagamento',
            style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold),
          ),
          const SizedBox(height: 24),
          PaymentOption(
            icon: Icons.credit_card,
            title: 'Cartão de Crédito',
            onTap: () => _makePayment('CARD'),
          ),
          PaymentOption(
            icon: Icons.credit_card_off,
            title: 'Cartão de Débito',
            onTap: () => _makePayment('CARD'), // Assuming debit also uses 'CARD' method
          ),
          PaymentOption(
            icon: Icons.pix,
            title: 'PIX',
            onTap: () => _makePayment('MULTICAIXA'), // Assuming PIX maps to MULTICAIXA
          ),
          PaymentOption(
            icon: Icons.money,
            title: 'Dinheiro',
            onTap: () => _makePayment('CASH'),
          ),
        ],
      ),
    );
  }
}

class PaymentOption extends StatelessWidget {
  final IconData icon;
  final String title;
  final VoidCallback onTap;

  const PaymentOption({
    super.key,
    required this.icon,
    required this.title,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    return Card(
      margin: const EdgeInsets.symmetric(vertical: 8.0),
      elevation: 2.0,
      child: ListTile(
        leading: Icon(icon, size: 40, color: Theme.of(context).primaryColor),
        title: Text(title, style: const TextStyle(fontSize: 18)),
        trailing: const Icon(Icons.arrow_forward_ios),
        onTap: onTap,
      ),
    );
  }
}
